---
- hosts: all
  gather_facts: True
  vars_files:
    - vars/config.yaml
  roles:
    - common
    - laggyluke.add-ssh-keys-from-github
    - volumes
    - { role: bonding, when: ohai_network.default_interface != "mgmt" }
