---
- name: uninstall nova python dependencies
  pip: requirements=/opt/{{ nova_branch }}/requirements.txt state=absent
  ignore_errors: True

- name: remove nova directories
  file: path={{ item }} state=absent
  with_items:
    - /opt/{{ nova_branch }}
    - /etc/nova
    - /var/log/nova
    - /var/lib/nova
