---
- name: create rpc deploy folder
  file: path=/var/lib/jenkins/rpc_deploy state=directory owner=jenkins mode=0755

- name: install rpc environment file
  template: src=rpc_environment.j2 dest=/var/lib/jenkins/rpc_deploy/rpc_environment.yml owner=jenkins mode=0644

- name: install rpc user config file
  template: src=rpc_user_config.j2 dest=/var/lib/jenkins/rpc_deploy/rpc_user_config.yml owner=jenkins mode=0644
