---
- name: install pip
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt: pkg=python-pip state=installed

- name: install pip
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum: pkg=$item state=installed
  with_items:
    - python-pip
    - libselinux-python

- name: install vim
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt: pkg=vim state=installed

- name: install vim
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum: pkg=vim state=installed

- name: disable selinux enforcement
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  selinux: policy=targeted state=permissive

- name: really disable selinux enforcement
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  command: setenforce 0
