---
- name: install useful packages
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt: pkg={{ item }} state=present
  with_items:
    - aptitude
    - bridge-utils
    - build-essential
    - git
    - ntp
    - ntpdate
    - python-dev
    - python-pip
    - ssh
    - sudo
    - vim

- name: install useful packages
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum: pkg={{ item }} state=present
  with_items:
    - yum
    - bridge-utils
    - build-essential
    - git
    - ntp
    - ntpdate
    - python-dev
    - python-pip
    - ssh
    - sudo
    - vim

- name: disable selinux enforcement
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  selinux: policy=targeted state=permissive

- name: really disable selinux enforcement
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  command: setenforce 0
