---
- host: deployment
  gather_facts: True
  roles:
    - deployment_networking

- hosts: all
  gather_facts: True
  vars_files:
    - vars/networking.yml
  roles:
    - networking
    # - { role: networking, when: ansible_default_ipv4.interface != "br-mgmt" }

